on:
  push:
    branches:
      - main
      - hotfix/*

name: Release
jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    if: github.event.created == false

    steps:
      - uses: googleapis/release-please-action@v4
        with:
          target-branch: ${{ github.ref_name }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
